""" tables_2

Revision ID: fdeb44a3c163
Revises: 64c2caf64827
Create Date: 2024-07-02 09:45:03.890125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdeb44a3c163'
down_revision: Union[str, None] = '64c2caf64827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'playlist', ['db_id'])
    op.create_unique_constraint(None, 'videos', ['db_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='unique')
    op.drop_constraint(None, 'playlist', type_='unique')
    # ### end Alembic commands ###
