name: video_membership CI/CD

on:
   push:
      branches:
         - "main"
         - "master"

jobs:

    Docker-deploy:
       runs-on: ubuntu-latest

       steps:
          - name: Checkout
            uses: actions/checkout@v4
      
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
               username: ${{ secrets.DOCKERHUB_USERNAME }}
               password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
      
          - name: Build and push
            uses: docker/build-push-action@v5
            with:
               context: .
               file: ./Dockerfile
               push: true
               tags: ${{ secrets.DOCKERHUB_USERNAME }}/pizza_delivery:latest

    Render-deployment:
       runs-on: ubuntu-latest
       needs: [Docker-deploy]

       environment: Render

       steps:
         - name: Get actions
           uses: actions/checkout@v4
         - name: Deploying to Render
           uses: johnbeynon/render-deploy-action@v0.0.8
           with:
             service-id: ${{secrets.RENDER_SERVICE_ID}}
             api-key: ${{secrets.RENDER_API_KEY}}

