name: pizzaAPI CI/CD

on:
   push:
      branches:
         - "main"
         - "master"

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
         - name: Push repo
           uses: actions/checkout@v4

         - name: Install Python
           uses: actions/setup-python@v5
           with:
              python-version: '3.10'
         - name: Upgrade Pip
           run: python -m pip install --upgrade pip
         - name: Install all dependencies
           run: pip install -r requirements.txt
    
    Docker-deploy:
       runs-on: ubuntu-latest

       steps:
          - name: Checkout
            uses: actions/checkout@v4
      
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
               username: ${{ secrets.DOCKERHUB_USERNAME }}
               password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
      
          - name: Build and push
            uses: docker/build-push-action@v5
            with:
               context: .
               file: ./Dockerfile
               push: true
               tags: ${{ secrets.DOCKERHUB_USERNAME }}/pizza_delivery:latest

    Back4app-deployment:
       runs-on: ubuntu-latest
       needs: [Docker-deploy]

       environment: Back4app

       steps:
          - name: Get actions
            uses: actions/checkout@v4
          - name: Deploying to Back4app
            uses: back4app/Github-Ci-Cd-Example@v1 #The action
            with:
               project: ${{secrets.NAME_PROJECT}}
               accountKey: ${{secrets.ACCOUNT_KEY}}
    
    Render-deployment:
       runs-on: ubuntu-latest
       needs: [build]

       environment: Render

       steps:
         - name: Get actions
           uses: actions/checkout@v4
         - name: Deploying to Render
           uses: johnbeynon/render-deploy-action@v0.0.8
           with:
             service-id: ${{secrets.RENDER_SERVICE_ID}}
             api-key: ${{secrets.RENDER_API_KEY}}

